### ISSUE TITLE
[Question]: Example networking stack using ProcedureKit

### ISSUE THREAD

**Issue by robfeldmann** [ProcedureKit/ProcedureKit#631] opened 2016-12-04 23:28 UTC
I'm trying to determine how I might create a networking stack using ProcedureKit and I'm struggling with the basics of connecting the result of my network request procedures to other procedures, such as a transform procedure. 

Ultimately, what I'm trying to do is use a `NetworkDataProcedure` to make a call to some endpoint that fetches some JSON from the server. I want to use a `NetworkProcedure` to get all the [automatic retry goodness and other benefits](https://github.com/ProcedureKit/ProcedureKit/pull/561#issuecomment-263030127) it provides.

I also want to create a `TransformProcedure<Data, JSONDictionary>` that takes the `Data` from the `NetworkDataProcedure` and converts it to JSON.

I’d like to connect these two operations via dependency injection, which should theoretically work since `NetworkDataProcedure` conforms to the `Output Procedure` protocol.

It seems I should be able to do something like this, but I get a compilation error `Ambiguous reference to member ‘injectResult(from:)’` on the last line:

```
let dataProcedure = NetworkDataProcedure(session: URLSession.shared, request: aRequest)

let networkProcedure = NetworkProcedure { dataProcedure }

let transformProcedure = TransformProcedure<Data, JSONDictionary?> {
            data in
            let json = try! JSONSerialization.jsonObject(with: data, options: [])
            return json as? JSONDictionary
        }

transformProcedure.injectResult(from: dataProcedure)
```

I'm just struggling with the basics here and am hoping someone can help point me in the right direction. Thanks!

**Comment by danthorpe** [comment] 2016-12-05 00:04
Hi @robfeldmann - this is a really good question, and the issue is not with your understanding, as what you want to do, _should_ be possible, but currently isn't as I will explain.

So, this is what we want...

```swift
let request = URLRequest(url: "http://www.apple.com")
let network = NetworkProcedure { NetworkDataProcedure(session: URLSession.shared, request: request) }

// Perform synchronous transform of Data
let transform = TransformProcedure<Data, Any> { try JSONSerialization.jsonObject(with: $0) }.injectResult(from: network)

queue.add(operations: network, transform)
```

Note that for `NetworkProcedure` (any `RepeatProcedure` subclass) to work correctly, you **need** to return a _new_ procedure from within the closure. Your example code, captures the same procedure which cannot be re-tried.

Anyway, the code above will not compile, because `NetworkProcedure` does not (currently) conform to `OutputProcedure` - as this is not an explicit requirement on its generic type, `T`. Swift does not allow conditional protocol conformance (i.e. inheritance). This means that the `injectResult(from:)` API is ambiguous, as the dependency does not conform to the required protocol.

Unfortunately, at the moment, the way around this, is to drop down to the lower level `inject(dependency:)` API, like this:

```swift
        let transform = TransformProcedure<Data, Any> { data in
            // Perform synchronous transform
            return try JSONSerialization.jsonObject(with: data)
        }.inject(dependency: network) { procedure, dependency, errors in
            // Check if there are any errors first
            guard errors.isEmpty else {
                procedure.cancel(withError: ProcedureKitError.dependency(finishedWithErrors: errors)); return
            }
            // Check that we have a result ready
            guard let result = dependency.output.value else {
                procedure.cancel(withError: ProcedureKitError.requirementNotSatisfied()); return
            }
            // Check that the result was successful
            guard let data = result.value?.payload else {
                // If not, check for an error
                if let error = result.error {
                    procedure.cancel(withError: ProcedureKitError.dependency(finishedWithErrors: [error]))
                }
                else {
                    procedure.cancel(withError: ProcedureKitError.requirementNotSatisfied())
                }
                return
            }

            // Given successfull output
            procedure.input = .ready(data)
        }
``` 

This is pretty much what `injectResult(from: )` does automatically - and clearly is not something which I'm suggesting you do, but just explaining what is happening behind the scenes.

So... what to do. I've been mulling this over for a bit, and I think ultimately, I will make it so that `NetworkProcedure` requires a `T` which conforms to `OutputProcedure` returning the correct `Output` type, which will then fully support what we want to do here.

The reason why `NetworkProcedure` is currently loosely generic over `T` is so that it can support arbitrary network procedures. However, ultimately, I don't think this flexibility need come at the expense of defining the output type, as custom network procedures can still utilise `HTTPPayloadResponse`.

**Comment by danthorpe** [comment] 2016-12-05 00:25
@robfeldmann try checking out the branch here: #632, you should now be able to do this:

```swift
let transform = TransformProcedure { try JSONSerialization.jsonObject(with: $0) }
    .injectPayload(fromNetwork: network)

```

**Comment by robfeldmann** [comment] 2016-12-05 12:08
@danthorpe Wow, thank you so much for the quick response and update! That worked perfectly. Also, thanks for this tip as well:

> Note that for NetworkProcedure (any RepeatProcedure subclass) to work correctly, you need to return a new procedure from within the closure. Your example code, captures the same procedure which cannot be re-tried.

**Comment by yageek** [comment] 2016-12-05 12:09
I have a sample code here using protocols and ProcedureKit for network calls. The core is located here: https://github.com/vitactiv/iOSApp/tree/develop/MediaServerKit and the usage here: https://github.com/vitactiv/iOSApp/tree/develop/iOSApp

**Comment by danthorpe** [comment] 2016-12-05 13:09
@robfeldmann - just got some tests to write, and it'll get merged into `development` today.

**Comment by danthorpe** [comment] 2016-12-05 13:09
@yageek - awesome, interesting, will take a look though here... 🙌

**Closed** 2016-12-05 14:01 UTC
Labels: enhancement, ProcedureKitNetwork, question

**Comment by danthorpe** [comment] 2016-12-05 14:03
@robfeldmann - this is closed, as your initial code samples should now all work correctly if you use `injectPayload(fromNetwork:)`.

**Comment by axello** [comment] 2017-02-06 14:33
@yageek : The vitactiv account seems to be offline or misspelled. Do you have the ProcedureKit examples by chance also in another repository? 
@danthorpe : I am migration a project using Operations to ProcedureKit and I must say: the path is troublesome and undocumented (IMHO). Is there some (beta) documentation which handles ProcedureKit and not the old Operations? Thanks.

**Comment by danthorpe** [comment] 2017-02-06 20:30
@axello - yeah, migrating from _Operations_ to _ProcedureKit_ is not documented at all yet, apart from in issues in this repository (which is not helpful at all!). Ideally, we'd have this done, but it's not in place yet. At the moment, we have a PR to merge, and then will create Beta 7 - there are breaking changes with regard to cancellation. Then, I *think* that is all the work for v4, and I will start updating the wiki in earnest.

Unfortunately, my availability has been significantly reduced in 2017, so I've not been able to spend as much time documented _ProcedureKit_ as intended.

To aid in this, if you have specific migration issues, or observations - please create a new issue to document which elements were not obvious, or required changing. This will be a big help for us to write up a migration document.

**Comment by axello** [comment] 2017-02-07 09:04
Okay I will do that. In the meantime *any* implementation of ProcedureKit outside of the unit tests would be helpful. Like a sample project. I am looking at @stevemcintosh EarthQuakes, but there are currently many compilation issues with that one.
