### ISSUE TITLE
Memory leaks highlighted by Visual Memory Debugger

### ISSUE THREAD

**Issue by leotumwattana** [ProcedureKit/ProcedureKit#622] opened 2016-11-29 11:01 UTC
With Swift 3 came all the new shiny tools to try. Lo and behold, visual memory debugger seems to be pointing to a lot of memory leaks for 4.0.0.beta.5. 

With the warnings I then tried to exercise ProcedureKit related code and found large unbound memory increases.

I'll try to list what I can:

- [ ] __NSCFString
- [ ] _ContiguousArrayStorage<AnyObserver<Procedure>>
- [ ] _ContiguousArrayStorage<NSOperation>
- [ ] _NativeSetStorageImpl<Condition>
- [ ] _NativeSetStorageImpl<NSOperation>
- [ ] _NativeSetStorageOwner<Condition>
- [ ] _NativeSetStorageOwner<NSOperation>
- [ ] AnyObserverBox<BackgroundObserver>
- [ ] AnyObserverBox<DidCancelObserver<GroupProcedure>>
- [ ] AnyObserverBox<DidCancelObserver<...>>
- [ ] AnyObserverBox<DidFinishObserver<Procedure>>
- [ ] AnyObserverBox<TimeoutObserver>
- [ ] AnyObserverBox<WillFinishObserver<...>>
- [ ] AnyObserverBox<WillFinishObserver<Procedure.EvaluateConditions>>
- [ ] AnyObserverBox<WillFinishObserver<Procedure>>
- [ ] BackgroundObserver
- [ ] Closure captures
- [ ] NSLock
- [ ] NSRecursiveLock
- [ ] Protector<[NSOperation]>
- [ ] Protector<Procedure.ProtectedProperties>
- [ ] _IteratorBox<_ClosureBasedIterator<CKFetchRecordChangesOperation>>
- [ ] _IteratorBox<_ClosureBasedIterator<CKModifyRecordsOperation>>
- [ ] _IteratorBox<_ClosureBasedIterator<CKModifyRecordZonesOperation>>
- [ ] _IteratorBox<_ClosureBasedIterator<CKModifySubscriptionsOperation>>
- [ ] _IteratorBox<_ClosureBasedIterator<CKQueryOperation>>
- [ ] _IteratorBox<_ClosureBasedIterator<Double>>
- [ ] _IteratorBox<MapIterator<(CKProcedure<CKFetchRecordChangesOperation>, Delay?), RepeatProcedurePayload<CKProcedure<CKFetchRecordChangesOperation>>>>
- [ ] _NativeDictionaryStorageImpl<CKError.Code, (CKFetchRecordChangesOperation, FetchRecordChangesError<CKServerChangeToken>, LoggerProtocol, (Delay?, (CKProcedure<CKFetchRecordChangesOperation>) -> ())) -> (Delay?, (CKProcedure<CKFetchRecordChangesOperation>) -> ())?>
- [ ] RetryIterator<CKProcedure<CKFetchRecordChangesOperation>>
- [ ] CloudKitRecovery<CKFetchRecordChangesOperation>

There seems to be a lot more that are related to ProcedureKit. However, mostly around AnyObserverBox, InteratorBox, Protector, RetryIterator, CloudKitRecovery, etc.

I'll stop with the list above for now. I'm guessing a lot of them are related and it's kind of hard to group them just looking at the list.

**Comment by danthorpe** [comment] 2016-11-29 14:04
Thanks @leotumwattana - will start looking into these.

**Comment by swiftlyfalling** [comment] 2016-11-29 19:21
@danthorpe: I'm pretty sure that one of the problems is TimeoutObserver.

**Comment by swiftlyfalling** [comment] 2016-11-29 19:43
@leotumwattana: Could you do me a favor and try the `feature/OPR-622_memory_leaks` branch? It should, at a minimum, improve things.

**Comment by leotumwattana** [comment] 2016-11-29 21:46
@swiftlyfalling: Of course. This seems to have fixed about 32 of the memory leaks. Around 60 or so still related to ProcedureKit. Some other leaks are coming from other frameworks.

Next big chunk seems to be around 

1. `_IteratorBox` from `RetryProcedure`?
2. `AnyObserverBox` relating to general `willFinish/didFinish/didCancel` observers.

**Comment by swiftlyfalling** [comment] 2016-11-29 22:26
@leotumwattana: Any chance you have a simple repro case that exhibits these issues? Would be super helpful. 😊

**Comment by leotumwattana** [comment] 2016-11-29 22:50
@swiftlyfalling: Let me see what I can do. ;)

**Comment by leotumwattana** [comment] 2016-11-30 00:08
Here's a simple sample project that illustrates a good chunk of the leaks:
https://github.com/leotumwattana/ProcedureKitMemoryLeaks

I found that *Visual Memory Debugger* sometimes does not behave and will either not show anything or not show warnings (at least until I restart my machine). It seems *Leaks Instruments* is more consistent. 

The sample project will create a default record zone on CloudKit. You’ll have to add your own Signing for development team. Let me know what else I can do to help. 

Thanks @swiftlyfalling & @danthorpe.

**Comment by swiftlyfalling** [comment] 2016-11-30 01:48
@leotumwattana: Pushed another fix to the `feature/OPR-622_memory_leaks` branch. Should resolve a number of additional leaks.

**Comment by leotumwattana** [comment] 2016-11-30 09:20
Roger that. Let's fix what we can and leave the Swift stuff for the Swift team. ;)

Here are some of the remaining leaks as reported from Instruments. Think I'll try including them as screenshots this time:

![instruments12](https://cloud.githubusercontent.com/assets/544211/20746510/15c2f102-b721-11e6-8f5a-7014a7a6e5ce.png)
![instruments12 2](https://cloud.githubusercontent.com/assets/544211/20746509/15c2e6f8-b721-11e6-9799-f7ca140e0eaa.png)
![instruments12 3](https://cloud.githubusercontent.com/assets/544211/20746511/15c424e6-b721-11e6-87c1-9b654e433766.png)
![instruments12 4](https://cloud.githubusercontent.com/assets/544211/20746514/15c9207c-b721-11e6-97b9-a08f07a97b59.png)
![instruments12 5](https://cloud.githubusercontent.com/assets/544211/20746512/15c49fb6-b721-11e6-96e5-7f7719c98b75.png)
![instruments12 6](https://cloud.githubusercontent.com/assets/544211/20746513/15c583fe-b721-11e6-95ab-cfea24542fa3.png)
![instruments12 7](https://cloud.githubusercontent.com/assets/544211/20746515/15e90e6e-b721-11e6-80f8-9efc2b58605b.png)
![instruments12 8](https://cloud.githubusercontent.com/assets/544211/20746516/15ea53e6-b721-11e6-990e-f75f1ded446b.png)
![instruments12 9](https://cloud.githubusercontent.com/assets/544211/20746517/15eac344-b721-11e6-9b12-cc090e31c481.png)
![instruments12 10](https://cloud.githubusercontent.com/assets/544211/20746518/15ede182-b721-11e6-96aa-f95c55eea762.png)
![instruments12 11](https://cloud.githubusercontent.com/assets/544211/20746519/15edfba4-b721-11e6-83eb-d66bbef3e9ec.png)
![instruments12 12](https://cloud.githubusercontent.com/assets/544211/20746520/15effd5a-b721-11e6-964e-f0192c60b70f.png)
![instruments12 13](https://cloud.githubusercontent.com/assets/544211/20746521/1610871e-b721-11e6-945c-01633899d43f.png)
![instruments12 14](https://cloud.githubusercontent.com/assets/544211/20746523/161242a2-b721-11e6-889e-2d636712f4d6.png)
![instruments12 15](https://cloud.githubusercontent.com/assets/544211/20746522/1610b400-b721-11e6-8182-27f6264cfbd7.png)
![instruments12 16](https://cloud.githubusercontent.com/assets/544211/20746526/1617a45e-b721-11e6-86c6-a386f330aac5.png)
![instruments12 17](https://cloud.githubusercontent.com/assets/544211/20746524/1616efbe-b721-11e6-9c69-746c4426ac90.png)
![instruments12 18](https://cloud.githubusercontent.com/assets/544211/20746525/16178974-b721-11e6-9c38-15b4e2a83a7f.png)
![_nativesetstorageowner condition](https://cloud.githubusercontent.com/assets/544211/20746527/163689e6-b721-11e6-9a01-6b2c93f9ea07.png)
![instruments12 19](https://cloud.githubusercontent.com/assets/544211/20746528/1636878e-b721-11e6-93d1-4d0512237a52.png)
![instruments12 20](https://cloud.githubusercontent.com/assets/544211/20746529/16396c88-b721-11e6-8636-54f07722e688.png)
![instruments12 21](https://cloud.githubusercontent.com/assets/544211/20746530/163f5332-b721-11e6-9be0-e188dc83cfc1.png)

**Comment by danthorpe** [comment] 2016-11-30 13:59
Going through @leotumwattana sample project - great stuff by the way. I think a large part of the issue is that `GroupProcedure` keeps it's children in a thread safe `Protector`.

So, `GroupProcedure` owns `Protector<[Operation]>`, and a queue. The `Protector` holds onto this array as its `ward`, and the operations are also owned by the queue. So, there is a cycle here too.

I've confirmed this as much as just swapping out the `GroupProcedure` with an `AsyncBlockProcedure`, and now I've only got one leak (some other issue with the log's queue).

So, will investigate supporting weak references in the `Protector` for the group children.

**Comment by danthorpe** [comment] 2016-12-05 15:05
So, after discussions on Slack, it turns out that this is all issues in Instruments. Not really sure where we stand with this issue, now - in terms of reporting the bugs to Apple. However, to avoid confusions for _ProcedureKit_ consumers, I'm going to close this.

**Closed by danthorpe** 2016-12-05 15:05 UTC
Labels: bug

**Comment by leotumwattana** [comment] 2016-12-05 15:30
Yup. I agree on not confusing framework consumers and closing this issue.

Just to conclude. This issue ended up encompassing two sets of issues:
1. Actual memory leaks that was fixed by @swiftlyfalling. Many 👍 
2. A group of "fake" issues due to Instruments / Visual Memory Debugger

🎉🎉🎉

**Comment by swiftlyfalling** [comment] 2016-12-22 19:55
As an update, Xcode 8.2 further reduces the spurious (incorrect) memory leaks displayed while Procedures are executing - although there are a handful remaining. Will look into packaging up a repro case and submitting a Swift/Xcode bug report.

**Comment by danthorpe** [comment] 2016-12-22 20:08
@swiftlyfalling that would be awesome. 😃
