### ISSUE TITLE
`injectResult` retain cycle

### ISSUE THREAD

**Issue by kdubb** [ProcedureKit/ProcedureKit#897] opened 2018-10-10 05:12 UTC
With the following code...
```swift
class FetchContentMessageProcedure: GroupProcedure {

  init(_ ctx: MessageContext, summary: MessageSummary) {
    
    let resolveProc = ResolveRoutingProcedure(ctx, aliases: [summary.senderAlias])
    let processProc = ContentMessageProcessProcedure(ctx, summary: summary)
    processProc.injectResult(from: resolveProc)

    let ackProc = AcknowledgeMessageProcedure(ctx, messageId: summary.id, onOrBefore: summary.sent)
    ackProc.addDependency(processProc)

    super.init(operations: [resolveProc, processProc, ackProc])
  }

}
```
neither `ResolveRoutingProcedure` nor `ContentMessageProcessProcedure` are being released properly.

Replacing the `injectResult` line with the following (not suggesting it's a perfectly "correct" solution):
```swift
    processProc.addDependency(resolveProc)
    resolveProc.addCompletionBlock {
      processProc.input = .ready(resolveProc.output.success!)
    }
```
seems to solve the issue.

**Comment by kdubb** [comment] 2018-10-10 05:15
The offending block appears to be here...
https://github.com/ProcedureKit/ProcedureKit/blob/2bf45aac793c6cb035743d953fe1fbef392a5fc7/Sources/ProcedureKit/ProcedureResult.swift#L195


Adding a `[weak self]` to this block & appropriate strong capture when using `self` the procedures are released correctly.

**Comment by danthorpe** [comment] 2018-10-10 06:09
Thanks @kdubb - yes, definitely a bug. Fixing it now.

**Comment by danthorpe** [comment] 2018-10-10 07:54
@kdubb - can you try your code against the branch in #898?

I did write a unit test in an attempt to catch this error - but found it a little bit inconclusive. So will continue testing in my own projects.

I'm pretty sure the error is caused by the `self` which is passed into the block, this is a mistake, as it should use the `procedure` argument which it receives and is already weak.

**Comment by kdubb** [comment] 2018-10-10 08:07
Yep. Appears to work for me! Thanks!

**Comment by danthorpe** [comment] 2018-10-10 08:10
Thanks @kdubb - will aim to merge this branch into `development` asap.

**Comment by danthorpe** [comment] 2018-10-18 12:09
Closing this now, as the fix is merged.

**Closed by danthorpe** 2018-10-18 12:09 UTC
Labels: bug, waiting for response
