### ISSUE TITLE
Enhancements for Location Operations

### ISSUE THREAD

**Issue by jshier** [ProcedureKit/ProcedureKit#217] opened 2016-03-07 19:04 UTC
I've encountered an issue and I'm not sure what I need exists at the moment. Essentially, we're seeing `UserLocationOperation`s take longer than desired for some reason. I'd like to have the ability to cancel that operation (really any operation) if they take too long, and not have to build the operation with that in mind. It seems like either an observer that would start an internal timer, or a sequence of operations would be what's needed here, but I was wondering if you had any ideas. I'll get started on the observer and I'll see how that goes and post back.

**Comment by danthorpe** [comment] 2016-03-07 19:20
Hi @jshier - good question!

There is already a `TimeoutObserver` which you could attach and then use to trigger a retry or inform the user.

I have though that `Operation` should just have this kind of thing built into it - but seems like any default timeout would be highly dependent on the use case, and so I think it's best left to the framework consumer at this point.

Perhaps some operations like `UserLocationOperation` aught to have it set by default?

So, you could try something like this for now:

```swift
let location = RetryOperation {
   let op = UserLocationOperation()
   op.addObserver(TimeoutObserver(timeout: 6.0)
   return op
}
```

not tried that, but it's maybe a good starting point?

**Comment by jshier** [comment] 2016-03-07 19:21
Sorry, that's exactly what I need. I'll try it out and see how it works.

**Comment by danthorpe** [comment] 2016-03-07 19:28
Okay - you will need to inject a block into the `UserLocationOperation` to get the location out of it.

So, you might want to write an extension like this:

```swift
extension RetryOperation where T: UserLocationOperation {
   // Add APIs here to do stuff on your retrying location operation.
   // take a look at `CloudKitOperation` to see how to maintain configuration info
   // for subsequent retry attempts.

   func setTimeout(interval: NSTimeInterval) {
        addConfigureBlock {
            addObserver(TimeoutObserver(interval: interval))
        }
    }
}
```

**Comment by jshier** [comment] 2016-03-07 19:46
My `UserLocationOperation` is already in a `GroupOperation`, as I chain a network request that needs the location right after it. However, I've run into an interesting issue with `UserLocationOperation` and a timeout: the possible prompt for permission. In my scenario, the time it takes for the user to approve or deny location permissions should not be counted against the timeout. Using a simple `TimeoutObserver` it is, which is less than ideal. Any ideas on how to work around that?

**Comment by danthorpe** [comment] 2016-03-07 20:11
Hmm, yeah, that is less than idea. In which case, add the condition to your `GroupOperation`.

```swift
class LocationGroupOperation: GroupOperation {
    let location: UserLocationOperation
    override init() {
        location = UserLocationOperation()
        super.init(operations: [location])
        name = "Location Group Operation"
        addCondition(AuthorizedFor(Capability.Location(.WhenInUse)))
    }
}
```

**Comment by jshier** [comment] 2016-03-07 21:56
Tried this and got some rather unexpected behavior:
```
2016-03-07 21:12:45.868: Authorize Location.WhenInUse:  >>> MutuallyExclusive<_LocationCapability<CLLocationManager>>
2016-03-07 21:12:45.869: Authorize Location.WhenInUse: Initialized -> Pending
2016-03-07 21:12:45.869: Authorize Location.WhenInUse: Pending -> EvaluatingConditions
2016-03-07 21:12:45.869: GroupOperation: Initialized -> Pending
2016-03-07 21:12:45.869: Authorize Location.WhenInUse: EvaluatingConditions -> Ready
2016-03-07 21:12:45.869: Authorize Location.WhenInUse: Ready -> Executing
2016-03-07 21:12:45.869: Authorize Location.WhenInUse: Will Execute
2016-03-07 21:12:45.872: Authorize Location.WhenInUse: Executing -> Finishing
2016-03-07 21:12:45.872: Authorize Location.WhenInUse: Finishing with no errors.
2016-03-07 21:12:45.873: Authorize Location.WhenInUse: Finishing -> Finished
2016-03-07 21:12:45.873: Authorize Location.WhenInUse:  <<< MutuallyExclusive<_LocationCapability<CLLocationManager>>
2016-03-07 21:12:45.873: GroupOperation: Pending -> EvaluatingConditions
2016-03-07 21:12:45.873: GroupOperation: EvaluatingConditions -> Ready
2016-03-07 21:12:45.873: GroupOperation: Ready -> Finishing
2016-03-07 21:12:45.874: GroupOperation: Finishing with errors: [Operations.CapabilityError<Operations._LocationCapability<CLLocationManager>>.AuthorizationNotGranted(__C.CLAuthorizationStatus, Optional(Operations.LocationUsage.WhenInUse))].
2016-03-07 21:12:45.874: GroupOperation: Finishing -> Finished
2016-03-07 21:12:45.874: GroupOperation: finished with start time of 0 and error: 1 error(s): [Operations.CapabilityError<Operations._LocationCapability<CLLocationManager>>.AuthorizationNotGranted(__C.CLAuthorizationStatus, Optional(Operations.LocationUsage.WhenInUse))].
```
The condition fires, and the permissions prompt shows up, but the condition immediately fails and the operation immediately finishes. I'm also not sure this is what I want, since I want the network operation that depends on the location to run regardless of whether we got a location. I'll try adding an empty `BlockOperation` with the condition and see if that works.

**Comment by danthorpe** [comment] 2016-03-07 21:59
Hmm, that's weird. So you don't get an opportunity to tap the alert?

I wonder if this is a regression which we've not noticed?

I guess, seeing as you've got a `GroupOperation` adding an empty `BlockOperation` to your group first, and add this as the dependency to your `UserLocationOperation` will help trying to figure out what is going on.

But, this should work, so there is a bug somewhere.... 🤔

**Comment by jshier** [comment] 2016-03-07 23:18
Well, the prompt shows up and I can tap it, but whatever choice I make, the operation has finished, so nothing ever completes. Let me do some refactoring and also test on a device (this was the simulator) and I'll see what comes out.

**Comment by danthorpe** [comment] 2016-03-07 23:21
You can also play with [Permissions example](https://github.com/danthorpe/Examples/tree/development/Operations/Permissions) which has a `UserLocationOperation` setup.

I almost certainly would not trust behavior in the simulator when playing around with `CLLocationManager` - best to test this sort of thing on a real device.

**Comment by jshier** [comment] 2016-03-08 00:17
Adding the condition to the `GroupOperation` didn't work on device either, the behavior was the same. However, adding an empty `BlockOperation` that has the condition and which the `UserLocationOperation` has as a dependency gave me the behavior I wanted. As seen here:
```swift
class AGroupOperation : GroupOperation {
    let reason: String
    let details: String
    let completionHandler: AGroupCompletionHandler
    
    let locationOperation: UserLocationOperation
    
    init(reason: String, details: String, completionHandler: AGroupCompletionHandler) {
        self.reason = reason
        self.details = details
        self.completionHandler = completionHandler
        
        // Prompt for permissions from this operation, not the location operation, to avoid the timeout.
        let blockOperation = BlockOperation()
        blockOperation.name = "EmptyOperationForLocationPermissions"
        blockOperation.addLoggingObserver()
        blockOperation.addCondition(AuthorizedFor(Capability.Location(.WhenInUse)))
        
        locationOperation = UserLocationOperation(accuracy: kCLLocationAccuracyHundredMeters)
        locationOperation.addLoggingObserver()
        locationOperation.addObserver(TimeoutObserver(timeout: 8))
        locationOperation.addDependency(blockOperation)
        super.init(operations: [blockOperation, locationOperation])
        
        name = "AGroupOperation"

        addLoggingObserver()
    }
    
    override func willFinishOperation(operation: NSOperation, withErrors errors: [ErrorType]) {
        guard !cancelled else { return }
        
        guard operation === locationOperation && !operation.cancelled else { return }
        
        let coordinates = locationOperation.location?.coordinate ?? CLLocationCoordinate2D(latitude: 0, longitude: 0)
        
        let operation = ANetworkOperation(reason: reason, details: details, coordinates: coordinates, completionHandler: completionHandler)
        addOperation(operation)
    }
}
```

**Comment by jshier** [comment] 2016-03-08 00:22
Overall I think the `TimeoutObserver` is a good start (I would like to see it call it's cancellation on the same queue the observed operation is being executed on, but that would require a bit more of a refactor and I'm not sure there's actually a benefit) but it certainly seems like `UserLocationOperation` could use it's own timeout mechanism.

**Comment by gvarela** [comment] 2016-03-24 19:18
I had to write my own location operation because it takes a bit for the location manager to report speed. So, I had to create an internal timeout that would finish the operation with whatever location I last received if I don't get my ideal coordinates.

**Comment by danthorpe** [comment] 2016-03-24 19:28
@gvarela I expect in most cases that is what would be done, framework consumers would create their own `LocationManager` class to keep hold of previously retrieved `CLLocation` instances.

Did you create your own `Operation` subclass though? Or did you subclass `UserLocationOperation`? Really interested to hear what you had to do - as there is always potential to improve things here.

**Comment by gvarela** [comment] 2016-03-24 19:42
I originally started using the UserLocationOperation and used DidStartObserver to tweak the accuracy (because best and best for navigation return -1 and -2 respectively). But, when I need to ensure I was getting speed (which takes a second or two) I just copied over the class into my own project and tweaked the logic to fit my needs which included an internal timeout.

**Comment by danthorpe** [comment] 2016-03-24 19:47
Okay - I'm just thinking in terms of a feature request for `UserLocationOperation` v3.0 what do we want?

- [ ] Automatic timeout with configurable but sensible default value
- [ ] Automatic cache of previously received locations - available immediately.
- [ ] Return the best result when timeout is reached even if the desired accuracy is not met.

**Comment by gvarela** [comment] 2016-03-24 19:51
For the last one consideration needs to be made when CLLocationManager accuracy is set to kCLLocationAccuracyBest and kCLLocationAccuracyBestForNavigation which return -1 and -2. So, accuracy will never meet that criteria.

**Comment by danthorpe** [comment] 2016-03-24 19:52
Right - sorry - yes, bit slow over here - only just got why those numbers are significant! I did not know that!

Will get working on this after sorting out Swift 2.2

**Comment by danthorpe** [comment] 2016-03-24 20:00
So, the `.Best` and `.BestForNavigation` are really more suited to longer running processes - because they should *never* end but just always report their locations. So, it would need some special handling (basically just immediately return).

`UserLocationOperation` is not really the tool for a navigation focused location operation. However, a `RepeatedOperation` subclass which repeats `UserLocationOperation` subclasses periodically, based on the accuracy/speed of the previous result, could be interesting...

**Comment by gvarela** [comment] 2016-03-24 20:03
Yeah, it's one reason I used my own. If you are trying to save battery but need the accuracy (bestfornavigation uses wifi, bluetooth and GPS) but, run location updates in the background for extended periods of time this becomes critical. Again mine is a special case as I am doing passive tracking for an app that is trying to collocate the phone with a car for preventing texting while driving.

**Comment by danthorpe** [comment] 2016-03-24 20:11
Hmm, I that is a good line to draw actually. 

It's pretty specialist functionality, and I don't really want to start implementing stuff that is so specialist in a framework.

So, probably the best change would be to remove the convenience initializers - to make it easier to subclass `UserLocationOperation` and provide a public function which evaluates the received location and returns a Bool. This would be used to indicate whether the operation should finish.

```swift
func shouldFinishAfterReceivingLocation(location: CLLocation) -> Bool {
    // Default implementation would check the desired accuracy
    // Return true if `.Best` or `.BestForNavigation`
    // Return true if location.accuracy is good enough.
}
```

This would make subclassing much easier for consumers that need specialist behavior - as they can just override that method to determine their own accuracy acceptance criteria.

**Comment by danthorpe** [comment] 2016-10-09 20:13
I know this has been a long time coming.. sorry!

But, can you take a look at `UserLocationProcedure` in #500 and advise on whether it offers the right level of customisability?

**Comment by danthorpe** [comment] 2016-10-13 17:33
I'm gonna close this, as I think the queries/issues are now resolved by `UserLocationProcedure`

**Closed by danthorpe** 2016-10-13 17:33 UTC
Labels: enhancement
