### ISSUE TITLE
Can't compile 4.0.0 beta 1 with carthage

### ISSUE THREAD

**Issue by brandonskane** [ProcedureKit/ProcedureKit#482] opened 2016-09-21 03:41 UTC
I get the following error when I try to build using `github "danthorpe/Operations" "4.0.0-beta-1"` in my cartfile

`1.	While running pass #3913 SILFunctionTransform "Simplify CFG" on SILFunction "@_TFC12ProcedureKit9Protector4readurfFxqd__qd__".

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/brandonskane/Projects/ios-genesis-app/GenesisApp/Carthage/Checkouts/Operations/ProcedureKit.xcodeproj -scheme ProcedureKit -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)`

<img width="1440" alt="screen shot 2016-09-20 at 11 40 33 pm" src="https://cloud.githubusercontent.com/assets/375155/18697028/adbcf912-7f8b-11e6-842a-86ac027f0dcd.png">

**Comment by danthorpe** [comment] 2016-09-21 04:30
Hi @brandonskane, thanks for this - I'm guessing that this is reproduced just by doing a Release build. Will investigate what the issue is in AnyObserver.

**Comment by jshier** [comment] 2016-09-22 18:59
Looks like this is an issue with optimized builds. Setting the optimization level to `-Onone` for ProcedureKit lets it build fine. I hate these types of bugs.

**Comment by danthorpe** [comment] 2016-09-22 22:08
Thanks @jshier - unfortunately not had any chance to look into this yet. Will get to it over the weekend. Want to finish up Beta 2 and get Carthage support done.

**Comment by danthorpe** [comment] 2016-09-24 15:31
This looks to be caused by this Swift 3.0 bug: https://bugs.swift.org/browse/SR-2623

**Comment by danthorpe** [comment] 2016-09-24 17:24
Okay, so this bug looks to be fixed in `master` now - however, building a Release with the most recent toolchain from 2016/09/21 causes a different crash with Release configuration.

**Comment by JamieWhite** [comment] 2016-09-26 14:54
So I know this isn't really a fix but I worked around this by forking and disabling optimisation in the Swift build settings.

**Comment by danthorpe** [comment] 2016-10-01 23:33
This is fixed in Beta 2 - see the notes in #493

**Closed by danthorpe** 2016-10-01 23:33 UTC
Labels: ProcedureKit
