### ISSUE TITLE
Error when Archiving project in Xcode 9

### ISSUE THREAD

**Issue by foffer** [ProcedureKit/ProcedureKit#765] opened 2017-07-23 14:08 UTC
When trying to Archive project for upload to iTunesConnect I get the below error. I am on the `development` branch using Xcode 9 Beta 3. I can build and run my code just fine on device or in the simulator, but for some reason it throws this error when archiving.

```
Undefined symbols for architecture arm64:
  "__T012ProcedureKit05GroupA0C19_procedureDidCancelySays5Error_pG20withAdditionalErrors_tF", referenced from:
      _OBJC_CLASS_$__TtC10Occasional20UploadGroupProcedure in UploadGroupProcedure.o
      _OBJC_CLASS_$__TtC10Occasional20SignInGroupProcedure in SignInGroupProcedure.o
      _OBJC_CLASS_$__TtC10Occasional22DownloadGroupProcedure in DownloadGroupProcedure.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by danthorpe** [comment] 2017-07-23 14:32
Hmm, hi @foffer - how are you integrating _ProcedureKit_? CocoaPods?

**Comment by foffer** [comment] 2017-07-23 14:38
Hi @danthorpe. Yes, I am just in the process of trying a full clean of the project derived data and redownloading all the pods to see if that helps. Otherwise I am a bit blank?

**Comment by danthorpe** [comment] 2017-07-23 14:40
Hmm, which commit are you pointing at on `development`?

**Comment by foffer** [comment] 2017-07-23 14:44
No specific commit, just using `:branch => "development"`

**Comment by danthorpe** [comment] 2017-07-23 14:46
Okay, well that API is from April.

I think possibly the issue is that it is marked `internal` - so, your application code should not have access to it?

**Comment by danthorpe** [comment] 2017-07-23 14:49
But I'm not sure why it would be compiling in `Debug` configuration otherwise....

**Comment by foffer** [comment] 2017-07-23 14:49
Is see, that would make sense. Should I be overriding the `cancel()` on the individual procedures instead of using overriding the GroupProcedure's didCancel?

**Comment by danthorpe** [comment] 2017-07-23 14:55
You should override [`child(_: Procedure, willFinishWithErrors: [Error])`](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/Group.swift#L199). You cannot override `cancel()` - it's `final`. You can add a `DidCancel` observer to either children, or the group. See also [Handling Cancellation](https://github.com/ProcedureKit/ProcedureKit/wiki/Handling-Cancellation).

**Comment by foffer** [comment] 2017-07-23 14:55
Ok, thanks @danthorpe, and sorry if it's just me being silly! Will report back asap if this resolved it!

**Comment by danthorpe** [comment] 2017-07-23 14:57
Cool - no worries, we're working on the docs and guides at the moment to make stuff like _how do I handle cancellation_ easier.

Also, to be clear, are you able to call `_procedureDidCancel(withAdditionalErrors:)` from within your `GroupProcedure` subclass? Because - that should not compile.... 🤔

**Comment by foffer** [comment] 2017-07-23 15:37
No, I was calling `override func procedureDidCancel(withErrors: [Error])`

**Comment by foffer** [comment] 2017-07-23 15:39
This is my class after I removed the `procedureDidCancel(withErrors: [Error])` call
```
class UploadGroupProcedure: GroupProcedure {
  private let storageRef = Storage.storage().reference(forURL: STORAGE_URL)
  private let logger = Logger(.uploads)
  private let imageManager = PHImageManager.default()
  
  
  let primaryKey: String
  init(uploadPrimaryKey: String, hasImageData: Bool = false) {
    
    self.primaryKey = uploadPrimaryKey
    logger.info("New upload procedure starting for upload %@", uploadPrimaryKey)

    if hasImageData {
      let getStoredData = GetStoredDataForUploadProcedure(primaryKey: uploadPrimaryKey)
      
      let uploadData = UploadDataProcedure(logger: logger, storageRef: storageRef)
      uploadData.injectResult(from: getStoredData)
      uploadData.add(dependency: getStoredData)
      uploadData.add(observer: NetworkObserver())
      
      let addUploadToDatabase = AddUploadToDatabaseProcedure(logger: logger, imageManager: imageManager, storageRef: storageRef)
      addUploadToDatabase.injectResult(from: uploadData)
      addUploadToDatabase.add(dependency: uploadData)
      addUploadToDatabase.add(observer: NetworkObserver())

      super.init(operations: [getStoredData, uploadData, addUploadToDatabase])
    } else {
      
      let checkForUpload = CheckForUpload(uploadPrimaryKey: uploadPrimaryKey)
      
      let getData = GetDataForUploadProcedure(logger: logger, imageManager: imageManager)
      getData.injectResult(from: checkForUpload)
      getData.add(dependency: checkForUpload)
      
      let uploadData = UploadDataProcedure(logger: logger, storageRef: storageRef)
      uploadData.injectResult(from: getData)
      uploadData.add(dependency: getData)
      uploadData.add(observer: NetworkObserver())
      
      let addUploadToDatabase = AddUploadToDatabaseProcedure(logger: logger, imageManager: imageManager, storageRef: storageRef)
      addUploadToDatabase.injectResult(from: uploadData)
      addUploadToDatabase.add(dependency: uploadData)
      addUploadToDatabase.add(observer: NetworkObserver())
      
      super.init(operations: [checkForUpload, getData, uploadData, addUploadToDatabase])
    }
  }
}
```

**Comment by swiftlyfalling** [comment] 2017-07-23 16:03
@foffer: Just to clarify, you were _calling_ `procedureDidCancel(withErrors:)`?

(Could you post your original code please?)

Because that function is for overriding in your subclass to *receive* the didCancel event. Internal framework code should be the only thing ever _calling_ it.

**Comment by foffer** [comment] 2017-07-23 16:08
Original code:

```
class UploadGroupProcedure: GroupProcedure {
  private let storageRef = Storage.storage().reference(forURL: STORAGE_URL)
  private let logger = Logger(.uploads)
  private let imageManager = PHImageManager.default()
  
  
  let primaryKey: String
  init(uploadPrimaryKey: String, hasImageData: Bool = false) {
    
    self.primaryKey = uploadPrimaryKey
    if hasImageData {
      let getStoredData = GetStoredDataForUploadProcedure(primaryKey: uploadPrimaryKey)
      
      let uploadData = UploadDataProcedure(logger: logger, storageRef: storageRef)
      uploadData.injectResult(from: getStoredData)
      uploadData.add(dependency: getStoredData)
      uploadData.add(observer: NetworkObserver())
      
      let addUploadToDatabase = AddUploadToDatabaseProcedure(logger: logger, imageManager: imageManager, storageRef: storageRef)
      addUploadToDatabase.injectResult(from: uploadData)
      addUploadToDatabase.add(dependency: uploadData)
      addUploadToDatabase.add(observer: NetworkObserver())

      super.init(operations: [getStoredData, uploadData, addUploadToDatabase])
    } else {
      
      let checkForUpload = CheckForUpload(uploadPrimaryKey: uploadPrimaryKey)
      
      let getData = GetDataForUploadProcedure(logger: logger, imageManager: imageManager)
      getData.injectResult(from: checkForUpload)
      getData.add(dependency: checkForUpload)
      
      let uploadData = UploadDataProcedure(logger: logger, storageRef: storageRef)
      uploadData.injectResult(from: getData)
      uploadData.add(dependency: getData)
      uploadData.add(observer: NetworkObserver())
      
      let addUploadToDatabase = AddUploadToDatabaseProcedure(logger: logger, imageManager: imageManager, storageRef: storageRef)
      addUploadToDatabase.injectResult(from: uploadData)
      addUploadToDatabase.add(dependency: uploadData)
      addUploadToDatabase.add(observer: NetworkObserver())
      
      super.init(operations: [checkForUpload, getData, uploadData, addUploadToDatabase])
    }
  }
  
  
  override func procedureDidFinish(withErrors: [Error]) {
    logger.error("Procedure(s) finished with errors: %@", withErrors)
  }
  
  override func procedureDidCancel(withErrors: [Error]) {
    // Do stuff
  }
```

**Comment by danthorpe** [comment] 2017-07-23 16:41
Hmm, that is weird - cannot see what the issue is....

**Comment by danthorpe** [comment] 2017-07-23 16:45
Also, @foffer, unrelated to your issue, but your code is pretty nice - exactly as intended. However, there are a few lines which are not needed. Every time you do this:

```swift
uploadData.injectResult(from: getStoredData)
```
The dependency relationship is automatically set - you don't then need the following line where you're adding a dependency.  👍

Also - kinda interested in what `Logger(.uploads)` is.. is that a custom logger?

**Comment by swiftlyfalling** [comment] 2017-07-23 16:55
@foffer: I just threw together a quick little test iOS app (with some GroupProcedure subclasses) and did an Archive build in Xcode, and I'm unable to reproduce the same issue. 🤔 I will note, however, that I did a *manual* install of ProcedureKit (download + drag the .xcodeproj into the new project).

**Comment by danthorpe** [comment] 2017-07-23 17:08
@foffer I've just done an Xcode Archive build of _TryProcedureKit_ which integrates via CocoaPods, using the `HEAD` of `development`. Although that is a Mac app.... 🤔

**Comment by foffer** [comment] 2017-07-23 20:03
@danthorpe @swiftlyfalling thanks alot for all the response (and the tip with the `injectResult` 👍🏼).

I suspect it might be something to do with [cocoapods rather than the framework](https://stackoverflow.com/questions/39871595/xcode-8-symbols-not-found-for-architecture-arm64-for-pods), although the fixes suggested in the post did not resolve anything for me.

Just out of interest, I have declared my Podfile as follows:
```
https://stackoverflow.com/questions/39871595/xcode-8-symbols-not-found-for-architecture-arm64-for-pods
```
Is anything out of the ordinary there?

**Comment by danthorpe** [comment] 2017-07-23 20:16
@foffer - nope that looks fine to me, although you don't actually need to specify both. `'ProcedureKit/Mobile'` depends on the base.

One possible option, is to install by copying the sources and dragging & dropping. Or using Carthage. 

There should be very limited changes to make to your code. The only thing you would need to do is use `import ProcedureKitMobile` in any of the files where you're using UIKit related stuff, like `AlertProcedure` or `NetworkActivityController .shared`. Then you can check if it is CocoaPods or not.

**Comment by foffer** [comment] 2017-07-23 20:25
Odd, if I specify just `ProcedureKit/Mobile` I run into [this issue](https://github.com/ProcedureKit/ProcedureKit/issues/752).

I will try a manual install or use Carthage tomorrow and report back. Thank you so much for all the help.

Oh, to answer your question re the logger, it's just a very small [wrapper around](https://gist.github.com/foffer/c4cb4ab19c805e0071be9bd2329231c4) os.log that I can then change out later if I decide to use a more feature rich logging framework.

**Comment by foffer** [comment] 2017-07-24 16:52
I just did a build and archive having added the .xcodeproj manually and it successfully completed. Cocoapods must've messed something up. I will try to investigate further

**Comment by danthorpe** [comment] 2017-07-24 16:56
Okay, well, that's good - but also bad. We have integration tests for CocoaPods - obviously they're not working completely! If you can let us know anything you find out - that would be great.

**Comment by foffer** [comment] 2017-07-24 19:49
I have a feeling this will be on my end of things (i.e. old pods hanging around etc.) than on your side, but I will investigate and report back

**Comment by danthorpe** [comment] 2017-07-28 20:58
Gonna close this for now - please re-open if it turns out to not be your own issue! Thanks!

**Comment by kdubb** [comment] 2017-08-11 03:59
This problem is a legitimate bug that I am encountering with `4.3.0` and Xcode 9.5 beta 5.

**Comment by kdubb** [comment] 2017-08-11 04:06
More information and a "fix"...

• It only occurs in "release" configuration; not sure which actual compiler option causes it
• It appears to be a swift generation or linking error
• By removing `final` from `Group.swift:147` the compilation succeeds
```swift
final internal override func _procedureDidCancel(withAdditionalErrors additionalErrors: [Error])
```

Surely `final` isn't _needed_ in this case because it's already internal.

**Comment by kdubb** [comment] 2017-08-11 04:08
A hotfix release for this would be _awesome_.  Although, given how it's been reported (OP was using Xcode 9 beta as well) it must not affect Xcode 8 people.

**Comment by jshier** [comment] 2017-08-11 04:14
In addition to whatever fix may be needed here, it should also be reported as a Swift bug.

As for a quick fix, does it still fail if the explicit `internal` is removed? `final` is useful to prevent even internal overrides, but the `internal` should be completely unnecessary. Unless the overridden declaration is public? Which would be odd, given the `_` naming.

**Comment by kdubb** [comment] 2017-08-11 04:29
I tried the second method of replacing `internal` with `public` and it works as well.

It seems like like making it `public` is a "lesser" solution because it leaves the methods callable from outside the module and they clearly should not be.

Removing `final` but keeping `internal` still hides these functions completely from the outside (in both `Procedure` and `GroupProcedure`); which precludes them from being overridden outside as well.

**Comment by jshier** [comment] 2017-08-11 04:34
Sorry, I meant try removing the `internal` and leave the `final` and see if that works. Just wondering if the combination of modifiers is causing an issue. Like I said, `internal` shouldn’t be necessary at all unless it’s mean to override a `public` super implementation, which this shouldn’t be.

**Comment by kdubb** [comment] 2017-08-11 04:38
I did try removing the explicit `internal`, which still assigns the methods internal access, and the error still surfaces.

**Comment by danthorpe** [comment] 2017-08-11 04:55
Will do a hot fix today. Great work on tracking it down! Will report back here. 

- but yeah, Swift bug (@jshier are you able to report to bugs.swift.org ?)
- will remove both final & internal specifies
- need to get Xcode 9 on our CI here - why this wasn't caught.

**Comment by jshier** [comment] 2017-08-11 05:00
I can tomorrow (for me), unless @swiftlyfalling gets to it first.

**Comment by danthorpe** [comment] 2017-08-11 17:50
@kdubb are you able to retest using this branch of PK from #785, `hotfix/4.3.0/OPR-765_remove_final`. Thanks!

**Comment by jshier** [comment] 2017-08-11 22:10
@kdubb Do you have a project which replicates this which was can use and attach to the Swift report. I can't replicate this issue on Xcode 9 beta 5 with a very simple test project. Perhaps I need a `GroupProcedure` subclass?

**Comment by kdubb** [comment] 2017-08-11 22:23
@jshier  Unfortunately nothing I can release but I can tell you it's not a "simple" setup.

The project has one private pod (call it `MyMod`) that depends on `ProcedureKit` and then an application target/module (`AppMod`) that also depends on `ProcedureKit`. Finally we have an application that uses both `AppMod` (in same workspace) and `MyMod` via cocoapods.

**Comment by kdubb** [comment] 2017-08-11 22:30
@danthorpe The hotfix branch works for me!

**Comment by danthorpe** [comment] 2017-08-12 08:30
@kdubb okay - hold tight - will release 4.3.1 asap.

@jshier - I'm assuming you'd need to be using a `GroupProcedure`?

**Comment by jshier** [comment] 2017-08-13 00:19
I tried a simple use, I'll try a more complete one.

**Comment by jshier** [comment] 2017-08-13 04:10
I can't reproduce this issue with a test app that uses a variety of frameworks and an app all depending on ProcedureKit. I'm wondering if this has something to do with how CoocaPods integrated frameworks work vs. project local ones, but I really don't know. I'll file the issue anyway.

[SwiftBugTest.zip](https://github.com/ProcedureKit/ProcedureKit/files/1220245/SwiftBugTest.zip)

**Comment by jshier** [comment] 2017-08-13 04:29
Reported as [SR-5679](https://bugs.swift.org/browse/SR-5679).

**Comment by danthorpe** [comment] 2017-08-13 14:22
v4.3.1 is released. 🎉🙌

Thanks for all your help everyone on this issue!

**Comment by danthorpe** [comment] 2017-08-15 18:38
There has been a comment on [SR-5679](https://bugs.swift.org/browse/SR-5679) that is not re-produceable in Beta 5.

@kdubb - can you re-produce with @jshier's demo app (linked to above)? You will need to change the Podfile to point to tag `4.3.0` for the failing version. If you cannot re-produce in the latest Xcode with a sample app (ours or yours) then we're at a dead end somewhat.

In which case, I would be inclined to revert the change made for 4.3.1, and put `final` back.

**Comment by danthorpe** [comment] 2018-10-18 12:12
Closing this for now...

**Closed by danthorpe** 2018-10-18 12:12 UTC
Labels: Xcode 9, bug, fixed
