### ISSUE TITLE
Revise open vs. public 

### ISSUE THREAD

**Issue by martnst** [ProcedureKit/ProcedureKit#529] opened 2016-10-19 13:06 UTC
I would like to create subclass of `BlockProcedure` which in it's `init` provides a block.  However since `BlockProcedure` is set public I officially can't. 

Example: 

```swift
class RegisterForRemoteNotificationsOperation: BlockProcedure {
    init() {
        super.init(block: { 
            NSApplication.shared().registerForRemoteNotifications(matching: .alert)
        })
    }
}
```

btw: The iOS equivalent of my `RegisterForRemoteNotificationsOperation` is a `GroupProcedure` with a more complicated setup.

**Comment by danthorpe** [comment] 2016-10-19 20:59
Hi @martnst - hmm, so the issue is that the `init` of the `BlockProcedure` is not open?

**Comment by martnst** [comment] 2016-10-19 21:01
Right, changing `BlockProcedure` and it's superclass `TransformProcedure` to open would be enough. Unless you have any concerns of having somebody subclass it.

**Comment by martnst** [comment] 2016-10-19 21:02
I picked the title more generic as you might use this opportunity to check other class as well.

**Comment by danthorpe** [comment] 2016-10-19 21:07
Yeah, I went though and made a bunch of classes `open` but didn't change all the initialisers.... 🙄

**Comment by martnst** [comment] 2016-10-19 21:10
Okay looks like you missed `Transform.swift` . 😉

**Comment by danthorpe** [comment] 2016-10-19 21:25
Okay - so, can I just check something? What version of _ProcedureKit_ are you using?

`BlockProcedure` does not inherit from `TransformProcedure` anymore, as of Beta 3. And both of these classes are open. 

Also, there is no such thing in Swift 3.0, as far as I can tell, as an `open` initializer. So, for example, `NSObject` does not have an "open" initializer.

**Comment by martnst** [comment] 2016-10-19 21:29
Okay looks like I am behind #516 from 6 days ago.  
I am on `pod 'ProcedureKit', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :branch => 'development'`

**Comment by danthorpe** [comment] 2016-10-19 21:30
Yeah - #510 and #511.

And you've run `pod install` again?

**Comment by martnst** [comment] 2016-10-19 21:41
👍🏼 `pod update ProcedureKit` did pull the latest and greatest updates.

**Comment by danthorpe** [comment] 2016-10-19 21:41
Ha! okay - gonna close this, as pretty sure it's already done - your class example should be possible.

**Comment by martnst** [comment] 2016-10-19 21:42
confirmed

**Closed by danthorpe** 2016-10-19 21:41 UTC
Labels: ProcedureKit
