### ISSUE TITLE
Framework integration

### ISSUE THREAD

**Issue by erdem-inan** [ProcedureKit/ProcedureKit#489] opened 2016-09-26 15:03 UTC
Hi,

Thank you for this awesome lib.

I am developing a framework that used you library (with carthage).
I try integrate my framework in a test project full in Swift, everything goes well, but when i try to integrate in an old project (objective-c) I get an error.
I notice, that when I build my framework, the "MY_FRAMEWORK_NAME-Swift.h" contains those lines:

```
@import Operations;

@interface Operation (SWIFT_EXTENSION(MY_FRAMEWORK_NAME))
@end

@interface Operation (SWIFT_EXTENSION(MY_FRAMEWORK_NAME))
@end
```
I am using other lib, but yours is the only one that appears in the "MY_FRAMEWORK_NAME-Swift.h". I need to remove those lines manually to make it work.

Could you help me with that ? Thank

**Comment by danthorpe** [comment] 2016-09-26 16:37
Hi @erdem-inan!

Would love to help you if I can, but, I'm not really even sure sure what the issue is. Are you saying that the test project in Objective-C which uses your framework, which uses _Operations_ then doesn't integrate/compile?

**Comment by erdem-inan** [comment] 2016-09-29 08:37
Exactly, 
The error is show on the lines a give to you. 
When i manually remove those line, everything work.

**Comment by danthorpe** [comment] 2016-09-29 11:11
Can you create a minimal example which shows this error?

**Comment by erdem-inan** [comment] 2016-09-29 11:13
Yes, but i will try to do it this weekend ! Thanks !

**Comment by erdem-inan** [comment] 2016-10-06 13:54
Hey, Sorry for the delay,
I finally think that the problem is coming from my side. I will investigate it much more and come back to you if needed :)

Thank any way

**Comment by danthorpe** [comment] 2016-10-09 20:19
Okay @erdem-inan will close this for now.

**Closed by danthorpe** 2016-10-09 20:19 UTC
Labels: Operations, question
